[tool.poetry]
name = "cve-2023-44487"
version = "0.1.0"
description = ""
authors = ["Prakhar A."]
readme = "README.md"
packages = [{include = "cve_2023_44487"}]

[tool.poetry.dependencies]
python = "^3.9"
twisted = "^23.8.0"
h2 = "^4.1.0"
pyopenssl = "^23.2.0"
service-identity = "^23.1.0"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
